version: '3.4'
services:
  api:
    ports:
      - "5000:5000"
    build:
      context: ../
      dockerfile: ./common/Dockerfile
      target: api
      args:
        API_PORT: 5000
        SERVICE_DIR: immuni_exposure_reporting
    environment:
      ENV: development
      EXPOSURE_MONGO_URL: "mongodb://mongo:27017"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.18-xenial
    ports:
      - "27017:27017"
